/**
 * Indian Currency Formatter with Bengali Numerals
 * Generated by Nemotron OpenCode for Tribeni Minati Foundation
 */

export interface CurrencyFormatOptions {
  showSymbol?: boolean;
  symbolPosition?: 'prefix' | 'suffix';
  decimalPlaces?: number;
  useIndianNotation?: boolean;
  minimumIntegerDigits?: number;
  decimalSeparator?: string;
  groupSeparator?: string;
  showZeroPaise?: boolean;
  roundToPaise?: boolean;
}

export interface FormattedCurrency {
  formatted: string;
  value: number;
  integerPart: string;
  decimalPart?: string;
  symbol: string;
  isNegative: boolean;
}

const BENGALI_DIGITS: Record<string, string> = {
  '0': '০',
  '1': '১',
  '2': '২',
  '3': '৩',
  '4': '৪',
  '5': '৫',
  '6': '৬',
  '7': '৭',
  '8': '৮',
  '9': '৯',
};

const DEFAULT_OPTIONS: Required<CurrencyFormatOptions> = {
  showSymbol: true,
  symbolPosition: 'prefix',
  decimalPlaces: 0,
  useIndianNotation: true,
  minimumIntegerDigits: 1,
  decimalSeparator: '.',
  groupSeparator: ',',
  showZeroPaise: false,
  roundToPaise: true,
};

const CURRENCY_SYMBOL = '₹';

export function toBengaliNumerals(input: string | number): string {
  const str = String(input);
  return str.replace(/[0-9]/g, (digit) => BENGALI_DIGITS[digit] ?? digit);
}

export function fromBengaliNumerals(input: string): string {
  const reverseMap: Record<string, string> = {
    '০': '0',
    '১': '1',
    '২': '2',
    '৩': '3',
    '৪': '4',
    '৫': '5',
    '৬': '6',
    '৭': '7',
    '৮': '8',
    '৯': '9',
  };
  return input.replace(/[০-৯]/g, (digit) => reverseMap[digit] ?? digit);
}

function formatIndianNumbering(num: number): string[] {
  const absNum = Math.abs(num);
  const groups: string[] = [];

  if (absNum >= 1_00_00_000) {
    const crores = Math.floor(absNum / 1_00_00_000);
    groups.push(String(crores));
    const remainder = absNum % 1_00_00_000;
    if (remainder > 0) {
      const lakhs = Math.floor(remainder / 1_00_000);
      groups.push(lakhs.toString().padStart(2, '0'));
      const thousandsRemainder = remainder % 1_00_000;
      if (thousandsRemainder > 0) {
        groups.push(Math.floor(thousandsRemainder / 1000).toString().padStart(2, '0'));
        groups.push((thousandsRemainder % 1000).toString().padStart(3, '0'));
      } else {
        groups.push('00', '000');
      }
    } else {
      groups.push('00', '00', '000');
    }
  } else if (absNum >= 1_00_000) {
    const lakhs = Math.floor(absNum / 1_00_000);
    groups.push(String(lakhs));
    const remainder = absNum % 1_00_000;
    if (remainder > 0) {
      groups.push(Math.floor(remainder / 1000).toString().padStart(2, '0'));
      groups.push((remainder % 1000).toString().padStart(3, '0'));
    } else {
      groups.push('00', '000');
    }
  } else if (absNum >= 1000) {
    groups.push(Math.floor(absNum / 1000).toString());
    groups.push((absNum % 1000).toString().padStart(3, '0'));
  } else {
    groups.push(String(absNum));
  }

  return groups;
}

export function formatBengaliCurrency(
  value: number,
  options: CurrencyFormatOptions = {}
): FormattedCurrency {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const isNegative = value < 0;
  const absValue = Math.abs(value);

  let workingValue = absValue;
  if (opts.roundToPaise) {
    workingValue = Math.round(absValue * 100) / 100;
  }

  const integerPart = Math.floor(workingValue);
  const decimalPart = workingValue - integerPart;

  const groups = formatIndianNumbering(integerPart);
  let formattedInteger = groups.join(opts.groupSeparator);

  if (formattedInteger.length < opts.minimumIntegerDigits) {
    formattedInteger = formattedInteger.padStart(opts.minimumIntegerDigits, '0');
  }

  const bengaliInteger = toBengaliNumerals(formattedInteger);
  let bengaliDecimal: string | undefined;
  let hasDecimal = false;

  if (opts.decimalPlaces > 0) {
    const decimalStr = decimalPart.toFixed(opts.decimalPlaces).slice(2);
    const decimalValue = parseInt(decimalStr, 10);
    if (decimalValue > 0 || opts.showZeroPaise) {
      hasDecimal = true;
      bengaliDecimal = toBengaliNumerals(decimalStr.padStart(opts.decimalPlaces, '0'));
    }
  }

  let formatted = bengaliInteger;
  if (hasDecimal && bengaliDecimal) {
    formatted += `${opts.decimalSeparator}${bengaliDecimal}`;
  }

  if (opts.showSymbol) {
    formatted = opts.symbolPosition === 'prefix' ? `${CURRENCY_SYMBOL}${formatted}` : `${formatted} ${CURRENCY_SYMBOL}`;
  }

  if (isNegative) {
    formatted = `-${formatted}`;
  }

  return {
    formatted,
    value,
    integerPart: bengaliInteger,
    decimalPart: bengaliDecimal,
    symbol: CURRENCY_SYMBOL,
    isNegative,
  };
}
